### ISSUE TITLE
Create a basic todo list task (chg-010-008)

### ISSUE THREAD

**Issue by Evanlab02** [LittleClumsy/ToDo_CLI#9]
### Narrative

As a user of ToDo CLI,
I want to be able to create a task for my to do list,
so that I can keep track of my tasks.

### Scenario 1

Given I have installed ToDo CLI,
When I run it with the argument '--create',
Then I should be able to create a new task by filling out input prompts.

### Acceptance Criteria

- [x] Add selected data storage string to config.json.
- [x] Do not prompt user if there is already a data storage string in the config.json.
- [x] Should prompt user for all required input, but only for one task.
- [x] Should append to tasks.json file with a task object.

**Comment by Evanlab02** [comment]
1. Research sys.argv (--create)
2. tasks.json

```json
[
    {
        "date": "2022-03-05",
        "name": "Do Laundry"
    },
    {
        "date": "2022-03-05",
        "name": "Go fishing"
    },
    {
        "date": "2022-03-05",
        "name": "This should be user input"
    }
]
```

**Comment by Evanlab02** [comment]
https://docs.python.org/3/library/sys.html?highlight=argv#sys.argv

**Comment by Evanlab02** [comment]
Adding content to json file

```python
config = read_config_file()
storage_path = config["data_storage"]
storage_file = f"{storage_path}/tasks.json"

tasks_data = read_json_file(storage_file)
# tasks_data should be [ ] at first

name = input("Enter Name")
date = input("Enter date") # 2022-03-21

new_task = {
  "name": name,
  "date": date
}

tasks_data.append(new_task)

write_json_file(storage_file, tasks_data)
```
